apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs-persisent-volume-claim
spec:
  volumeName: gogs-persisent-volume
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
