apiVersion: apps/v1
kind: Deployment # what to create?
metadata:
  labels:
  name: mariadb-deployment
spec: # specification for deployment resource
  replicas: 1 # how many replicas of pods we want to create
  selector:
    matchLabels:
      app: mariadb
  template: # blueprint for pods
    metadata:
      labels:
        app: mariadb # service will look for this label
    spec: # specification for pods
      restartPolicy: Always
      containers: # we can have one or more containers
      - name: mariadb
        image: mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gogs-mariadb-secret
              key: gogs-mariadb-password
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mariadb-storage
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-persisent-volume-claim
