apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-persisent-volume
  labels:
    type: local
spec:
  claimRef:
    namespace: default
    name: mariadb-persisent-volume-claim
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"
