apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-persisent-volume-claim
spec:
  volumeName: mariadb-persisent-volume
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
